### ISSUE TITLE
NullPointerExceptioncom.opentokreactnative.OTSessionManager in disconnectSession

### ISSUE THREAD

**Issue by steverob** [opentok/opentok-react-native#142]
When navigating away from a page that has an OT component that's still trying to establish a connection I get this exception and it crashes the app - 

```
EXCEPTION(most recent call first)
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.opentok.android.Session.disconnect()' on a null object reference
    at com.opentokreactnative.OTSessionManager.disconnectSession(OTSessionManager.java:205)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
    at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:789)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
    at android.os.Looper.loop(Looper.java:164)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
    at java.lang.Thread.run(Thread.java:764)
```

Can this be handled on the native side please? Or is there a better way to handle this from  our side?

Thanks @msach22

**Comment by msach22** [comment]
@steverob We would need to change the code on line 205(https://github.com/opentok/opentok-react-native/blob/master/android/src/main/java/com/opentokreactnative/OTSessionManager.java#L205) to the following to make it work:

```
if (mSession != null) {
 mSession.disconnect();
}
```

**Comment by msach22** [comment]
Fix: https://github.com/opentok/opentok-react-native/pull/143

This should go out with 0.8.3

**Comment by msach22** [comment]
This fix has been released.
