### ISSUE TITLE
Android app crashes when I try to launch video chat

### ISSUE THREAD

**Issue by charlesoma** [opentok/opentok-react-native#164]
# Bug Report

**Current behavior**
My app is a detached expokit app. When I load the app and get to the video call in genymotion emulator, it crashes the app the first time and subsequent times it works. But when I build and download the apk on my mobile device and try to use the video chat, it crashes the app always. It never works on my phone

**Steps to reproduce**
I simply use the basic video chat example in the sample repo. This is my opentok build.gradle 

`apply plugin: 'com.android.library'

def _ext = rootProject.ext
def _reactNativeVersion = _ext.has('reactNative') ? _ext.reactNative : '+'
def _compileSdkVersion = _ext.has('compileSdkVersion') ? _ext.compileSdkVersion : 26
def _buildToolsVersion = _ext.has('buildToolsVersion') ? _ext.buildToolsVersion : '26.0.2'
def _minSdkVersion = _ext.has('minSdkVersion') ? _ext.minSdkVersion : 16
def _targetSdkVersion = _ext.has('targetSdkVersion') ? _ext.targetSdkVersion : 26

android {
    compileSdkVersion _compileSdkVersion
    buildToolsVersion _buildToolsVersion

    defaultConfig {
        minSdkVersion _minSdkVersion
        targetSdkVersion _targetSdkVersion
        versionCode 1
        versionName "1.0"
    }
}

dependencies {
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.facebook.react:react-native:${_reactNativeVersion}"  // From node_modules
    compile 'com.opentok.android:opentok-android-sdk:2.14.0'
}`

And this is my render function

`render() {
    if (!this.state.isReady) {
      return <Loading />;
    }  
    return (
      <View style={{ flex: 1, flexDirection: 'row' }}>
        <OTSession apiKey={this.state.apiKey} sessionId={this.state.sessionId} token={this.state.token}>
          <OTPublisher style={{width: 200, height: 200}} />
          <OTSubscriber style={{ width: 200, height: 200 }} />
        </OTSession>
      </View>
    );
  }`

**Example Project**
> (If possible, please create an example project here on GitHub.com that exhibits the problematic behaviour, and link to it here in the bug report)

**What is the current *bug* behavior?**

App crashes with "Unfortunately, APP has stopped" when I try to load the video chat.

**What is the expected *correct* behavior?**
It should load the camera without errors

**Relevant logs and/or screenshots**
> (Paste any relevant logs - please use code blocks (```) to format console output,
logs, and code as it's very hard to read otherwise.)

**Comment by msach22** [comment]
@charlesoma Can you please share that you've run `react-native link opentok-react-native` ?

I ran the latest package on an Android device and I'm not seeing any issues. Do you think it's an issue with the sample?

**Comment by msach22** [comment]
Please also share which Android device you're running this on.

**Comment by charlesoma** [comment]
@msach22 Yes I have run `react-native link opentok-react-native`. I don't know if it's an issue with the sample. Everything seems okay with the sample. I have run this on Redmi 4x, Samsung J7, and Infinix hot 5. On all these devices I am getting the same behaviour.

**Comment by charlesoma** [comment]
@msach22 I am now doing this exactly as it is in the sample and still getting the error where the whole app crashes. This is my code below

<img width="853" alt="screen shot 2018-09-11 at 9 35 17 am" src="https://user-images.githubusercontent.com/25100102/45348343-4b75a580-b5a6-11e8-9c2d-26774e870f0d.png">

**Comment by charlesoma** [comment]
This is the error log I'm getting

`09-11 02:37:08.424 28547-28984/com.cchubnigeria.nimcure_caregiver E/BluetoothAdapter: Bluetooth binder is null
09-11 02:37:12.041 28547-28547/com.cchubnigeria.nimcure_caregiver E/unknown:ViewManager: Error while updating prop publisherId
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:80)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:129)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:48)
        at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:32)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:213)
        at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:152)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:815)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:928)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2100(UIViewOperationQueue.java:46)
        at com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded(UIViewOperationQueue.java:886)
        at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:21)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.opentok.android.Publisher.setStyle(java.lang.String, java.lang.String)' on a null object reference
        at com.opentokreactnative.OTPublisherLayout.createPublisherView(OTPublisherLayout.java:31)
        at com.opentokreactnative.OTPublisherViewManager.setPublisherId(OTPublisherViewManager.java:31)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:80) 
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:129) 
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:48) 
        at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:32) 
        at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:213) 
        at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:152) 
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:815) 
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:928) 
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2100(UIViewOperationQueue.java:46) 
        at com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded(UIViewOperationQueue.java:886) 
        at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:21) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6119) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
09-11 02:37:15.998 28547-28547/com.cchubnigeria.nimcure_caregiver E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.cchubnigeria.nimcure_caregiver, PID: 28547
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=0, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.cchubnigeria.nimcure_caregiver/host.exp.exponent.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void host.exp.exponent.utils.PermissionsHelper.onRequestPermissionsResult(int, java.lang.String[], int[])' on a null object reference
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4089)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4132)
        at android.app.ActivityThread.-wrap20(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1533)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void host.exp.exponent.utils.PermissionsHelper.onRequestPermissionsResult(int, java.lang.String[], int[])' on a null object reference
        at host.exp.expoview.Exponent.onRequestPermissionsResult(Exponent.java:256)
        at host.exp.exponent.experience.BaseExperienceActivity.onRequestPermissionsResult(BaseExperienceActivity.java:272)
        at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7084)
        at android.app.Activity.dispatchActivityResult(Activity.java:6936)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4085)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4132) 
        at android.app.ActivityThread.-wrap20(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1533) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6119) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
`

**Comment by msach22** [comment]
@charlesoma Thanks for sharing the logs. Could you please confirm that this is happening with the latest release (v0.8.4)?

**Comment by charlesoma** [comment]
Yes latest version. How can I get this to work please?
<img width="393" alt="screen shot 2018-09-12 at 9 30 57 am" src="https://user-images.githubusercontent.com/25100102/45412668-2b5de900-b66f-11e8-9a50-ded449087ab1.png">

**Comment by msach22** [comment]
@charlesoma I'm not sure why this is happening for you (this issue was for an older version of the sdk), but shouldn't exist now.

Can you please verify that you've linked the native modules on android with the current release?

**Comment by msach22** [comment]
@charlesoma Were you able to get this going? The `opentok-react-native` android code seems out of sync. Could you please try with a fresh project?

I'm going to go ahead and close the issue, but please feel free to re-open if it still persists.

**Comment by Taras-Tymchiy** [comment]
Had the same issue on detached expo app (v28). 
The problem was that on some android devices the camera access permission dialog wasn't shown. Implementing PermissionAwareActivity interface in the MainActivity class (like here https://github.com/expo/expo/issues/784#issuecomment-338824333) worked for me

**Comment by msach22** [comment]
@Taras-Tymchiy that's interesting because the permissions for Android are being handled via React Native and not the native layer. Maybe there is a bug for Android in React Native after you eject from Expo? 

To prevent this, we can handle the permissions in the native layer. Please do let me know if that's needed for you
