### ISSUE TITLE
Crash reports: com.opentokreactnative.OTSessionManager.disconnectSession -- Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object

### ISSUE THREAD

**Issue by sunweiyang** [opentok/opentok-react-native#537]
We're seeing a number of reports of Android crashes in production:

```
com.opentokreactnative.OTSessionManager.disconnectSession
OTSessionManager.java, line 281
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object 
```

Stack trace:
```
java.util.concurrent.ConcurrentHashMap.get ConcurrentHashMap.java:944
com.opentokreactnative.OTSessionManager.disconnectSession OTSessionManager.java:281
java.lang.reflect.Method.invoke Method.java
com.facebook.react.bridge.JavaMethodWrapper.invoke JavaMethodWrapper.java:372
com.facebook.react.bridge.JavaModuleWrapper.invoke JavaModuleWrapper.java:151
com.facebook.react.bridge.queue.NativeRunnable.run NativeRunnable.java
android.os.Handler.handleCallback Handler.java:873
android.os.Handler.dispatchMessage Handler.java:99
com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage MessageQueueThreadHandler.java:27
android.os.Looper.loop Looper.java:214
com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run MessageQueueThreadImpl.java:226
java.lang.Thread.run Thread.java:764
```

I've scanned past opentok-react-native issues, and I've only been able to find #142 from years ago, which is why I'm filing this new issue.

**Comment by vishalcodiant** [comment]
same issue occured

**Comment by sunweiyang** [comment]
This crash is still occasionally occuring on opentok-react-native 0.19.0 -- help would be appreciated.

**Comment by enricop89** [comment]
@sunweiyang are you still experiencing this issue?

**Comment by sunweiyang** [comment]
This is still happening, but we haven't updated opentok-react-native for our app beyond 0.19.0 yet. Do the new versions fix this issue?

**Comment by enricop89** [comment]
Probably, the latest version (0.20.1) has the latest native SDKs for Android and iOS. If you can test and get back to me, it would be very appreciated

**Comment by softfactree** [comment]
I experienced this crash. the app is using "opentok-react-native": "^2.25.1"
here is the stack trace
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
       at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
       at com.opentokreactnative.OTSessionManager.disconnectSession(:12)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(:148)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(:147)
       at com.facebook.jni.NativeRunnable.run(SourceFile)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage()
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(:37)
       at java.lang.Thread.run(Thread.java:1012)
```
Below is the entire stack trace
[com.app.test_issue_981cd17e1a490ede018a4f1c9df7bc1e_crash_session_64E9E05901C1000148378C86D4F45987_DNE_0_v2_stacktrace.txt](https://github.com/opentok/opentok-react-native/files/12445260/com.app.test_issue_981cd17e1a490ede018a4f1c9df7bc1e_crash_session_64E9E05901C1000148378C86D4F45987_DNE_0_v2_stacktrace.txt)
