### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: eglCreateWindowSurface: EGL error: 0x3003

### ISSUE THREAD

**Issue by Panda-ref** [opentok/opentok-react-native#588]
# Bug Report

```
"opentok-react-native": "^0.20.1",
com.opentok.android:opentok-android-sdk:2.21.4
```

**Relevant logs and/or screenshots**
```
Fatal Exception: java.lang.RuntimeException: eglCreateWindowSurface: EGL error: 0x3003
       at com.opentok.android.grafika.gles.EglCore.a(:35)
       at com.opentok.android.grafika.gles.EglCore.a(:50)
       at com.opentok.android.grafika.gles.a.a(:8)
       at com.opentok.android.grafika.gles.WindowSurface.<init>(:3)
       at com.opentok.android.TextureViewRenderer$Renderer.run(:16)
```

```
Device
Brand:samsung
Model:Galaxy Fold
Orientation: Portrait
RAM free: 4.06 GB
Disk free: 437.98 GB
Operating System
Version:Android 12
Orientation: Portrait
Rooted:No
```

**Comment by enricop89** [comment]
Can you provide steps to reproduce please?

**Comment by vineus** [comment]
hey @enricop89 !

I have the same issue, when the component is umounted:

```
10-27 16:26:24.794 26488 27125 E AndroidRuntime: FATAL EXCEPTION: Thread-46
10-27 16:26:24.794 26488 27125 E AndroidRuntime: Process: com.alan.mind.app.debug, PID: 26488
10-27 16:26:24.794 26488 27125 E AndroidRuntime: java.lang.RuntimeException: invalid surface: null
10-27 16:26:24.794 26488 27125 E AndroidRuntime:        at com.opentok.android.grafika.gles.EglCore.a(Unknown Source:28)
10-27 16:26:24.794 26488 27125 E AndroidRuntime:        at com.opentok.android.grafika.gles.a.a(Unknown Source:8)
10-27 16:26:24.794 26488 27125 E AndroidRuntime:        at com.opentok.android.grafika.gles.WindowSurface.<init>(Unknown Source:3)
10-27 16:26:24.794 26488 27125 E AndroidRuntime:        at com.opentok.android.TextureViewRenderer$Renderer.run(Unknown Source:16)
```

package version: `opentok-react-native: 0.20.4`

I have it only when

```
    <OTSession
   ....
         options={{ androidOnTop: "publisher", useTextureViews: true }}
```

if I remove `useTextureViews: true`: no issue

**Comment by devwithzachary** [comment]
Thank you for this, have you tested against the latest package version? 0.21.1

**Comment by vineus** [comment]
> Thank you for this, have you tested against the latest package version? 0.21.1

yes, same behavior on `"opentok-react-native": "0.21.1"`

**Comment by pietgk** [comment]
any status update?

**Comment by beHaze** [comment]
Please reach out to Vonage support (https://api.support.vonage.com/hc/en-us) if you’re still facing issues.
