### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException: Image is already closed

### ISSUE THREAD

**Issue by ankitbishtapollo** [opentok/opentok-react-native#644]
Fatal Exception: java.lang.IllegalStateException: Image is already closed
       at android.media.Image.throwISEIfImageIsInvalid(Image.java:79)
       at android.media.ImageReader$SurfaceImage.getPlanes(ImageReader.java:1272)
       at com.opentok.android.Camera2VideoCapturer$5.onImageAvailable(SourceFile:16)
       at android.media.ImageReader$1.run(ImageReader.java:916)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:240)
       at android.os.Looper.loop(Looper.java:351)
       at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by jeffswartz** [comment]
@ankitbishtapollo Can you provide more context?

**Comment by beHaze** [comment]
We haven't heard back from you for a while, so we're closing this issue for now. Please, reach out if you still need help.
