### ISSUE TITLE
Crashlytics error: com.opentok.android.Camera2VideoCapturer.stopCapture

### ISSUE THREAD

**Issue by cnx-caiobarroso** [opentok/opentok-react-native#676]
# Bug Report

**Current behavior**

There is no reproducible case, but crashlytics logs keeps growing.

**Steps to reproduce**

Can't reproduce locally.

**What is the current *bug* behavior?**
![image](https://github.com/opentok/opentok-react-native/assets/104463740/69a832c9-73ef-4b7d-a1cb-f57272086a66)
<img width="921" alt="image" src="https://github.com/opentok/opentok-react-native/assets/104463740/44572133-8eae-46d6-a551-9fe6dccba037">

**What is the expected *correct* behavior?**
No crashlytics error logs.

**Suggestions**
We could add an if condition to assert removal only if it was previously capturing video. Example:

OTScreenCapturer.java
```java
...

@Override
    public int stopCapture() {
        if(capturing){
            capturing = false;
            mHandler.removeCallbacks(newFrame);
        }
        return 0;
}
```

**Comment by marinaserranomontes** [comment]
Hi @cnx-caiobarroso 

Please, could you confirm if you are getting issues with the latest version v2.26.1 ?

Thanks

**Comment by beHaze** [comment]
Thanks for verifying @cnx-caiobarroso we'll investigate.

**Comment by jintgeorge** [comment]
Hi @cnx-caiobarroso Can you find out why the camera 1 is disabled? Is it due to some security concern(corporate policy etc..)?

**Comment by jintgeorge** [comment]
Hi @cnx-caiobarroso We had another similar issue reported with error camera is disabled due to policy. This can be due to scenario with corporate devices where the camera may be disabled by the administrator for security purposes. We already have a ticket to address this scenario and may be released in near future.

**Comment by cnx-caiobarroso** [comment]
Interesting... makes a lot of sense. Great! I'll be waiting anxiously for this to be fixed. In the meantime, if there is anything more that I can help, say the word!

**Comment by cnx-caiobarroso** [comment]
Oh, by the way on the same tree of crash logs regarding this issue, this other problem shows:

Fatal Exception: com.opentok.android.Camera2VideoCapturer$Camera2Exception: CAMERA_IN_USE (4): connectHelper:1898: Higher-priority client using camera, ID "1" currently unavailable
       at com.opentok.android.Camera2VideoCapturer.initCamera(:79)
       at com.opentok.android.Camera2VideoCapturer.a()
       at com.opentok.android.Camera2VideoCapturer.$r8$lambda$iZPyzxYK8LZvnz0l_i0v-wMBKYU()
       at com.opentok.android.Camera2VideoCapturer$$ExternalSyntheticLambda2.run(:2)
       at com.opentok.android.Camera2VideoCapturer.startCapture(:50)
       at com.opentok.android.PublisherKit.c(:4)
       at com.opentok.android.PublisherKit.$r8$lambda$uxAi0JWLDFGCk8olGpDhu5RomTA()
       at com.opentok.android.PublisherKit$$ExternalSyntheticLambda16.run(:2)
       at android.os.Handler.handleCallback(Handler.java:984)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loopOnce(Looper.java:238)
       at android.os.Looper.loop(Looper.java:357)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
       at java.lang.Thread.run(Thread.java:1012)

**Comment by beHaze** [comment]
If you're still having issues please reach out to Vonage support (https://api.support.vonage.com/hc/en-us) to investigate further.
